In [1]:
from tensorflow.keras.preprocessing.text import one_hot

/Users/ravi_medabalimi/Desktop/Udemy_KrishNaik_Courses/DL_For_NLP/ANN_Classification/venv-metal/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [35]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
for words in sent:
    print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


In [4]:
voc_size = 1000
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[216, 260, 249, 542],
 [216, 260, 249, 387],
 [216, 383, 249, 438],
 [356, 466, 690, 212, 590],
 [356, 466, 690, 212, 19],
 [171, 216, 945, 249, 385],
 [836, 247, 161, 212]]

In [5]:
### Word embeddings

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [25]:
sen_len = 8
embedded_docs = pad_sequences(one_hot_repr,maxlen=8,padding='pre')
embedded_docs

array([[  0,   0,   0,   0, 216, 260, 249, 542],
       [  0,   0,   0,   0, 216, 260, 249, 387],
       [  0,   0,   0,   0, 216, 383, 249, 438],
       [  0,   0,   0, 356, 466, 690, 212, 590],
       [  0,   0,   0, 356, 466, 690, 212,  19],
       [  0,   0,   0, 171, 216, 945, 249, 385],
       [  0,   0,   0,   0, 836, 247, 161, 212]], dtype=int32)

In [29]:
## Feat representation
dim =10
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sen_len))  # Removed 'input_length'
model.compile('adam', 'mse')

In [30]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
word_emd = model.predict(embedded_docs)
word_emd

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[-0.01389011,  0.02788332, -0.02969543, -0.0485443 ,
         -0.03481313, -0.03310708,  0.03633107, -0.03014453,
         -0.02766066, -0.02299315],
        [-0.01389011,  0.02788332, -0.02969543, -0.0485443 ,
         -0.03481313, -0.03310708,  0.03633107, -0.03014453,
         -0.02766066, -0.02299315],
        [-0.01389011,  0.02788332, -0.02969543, -0.0485443 ,
         -0.03481313, -0.03310708,  0.03633107, -0.03014453,
         -0.02766066, -0.02299315],
        [-0.01389011,  0.02788332, -0.02969543, -0.0485443 ,
         -0.03481313, -0.03310708,  0.03633107, -0.03014453,
         -0.02766066, -0.02299315],
        [ 0.0077992 , -0.01597269, -0.04821292, -0.01285702,
         -0.02233913,  0.02808546,  0.04386901, -0.01577348,
         -0.04859953,  0.04986824],
        [ 0.0414227 , -0.00700275, -0.01070601,  0.03538385,
         -0.03773081,  0.01695851, -0.01495393, -0.02533355,
         -0.0110355 , -0.0106918 ],
        [ 0.00632419, -0.02820213,  0.04238944,  0.0

In [32]:
word_emd.shape

(7, 8, 10)

In [33]:
word_emd[1]

array([[-0.01389011,  0.02788332, -0.02969543, -0.0485443 , -0.03481313,
        -0.03310708,  0.03633107, -0.03014453, -0.02766066, -0.02299315],
       [-0.01389011,  0.02788332, -0.02969543, -0.0485443 , -0.03481313,
        -0.03310708,  0.03633107, -0.03014453, -0.02766066, -0.02299315],
       [-0.01389011,  0.02788332, -0.02969543, -0.0485443 , -0.03481313,
        -0.03310708,  0.03633107, -0.03014453, -0.02766066, -0.02299315],
       [-0.01389011,  0.02788332, -0.02969543, -0.0485443 , -0.03481313,
        -0.03310708,  0.03633107, -0.03014453, -0.02766066, -0.02299315],
       [ 0.0077992 , -0.01597269, -0.04821292, -0.01285702, -0.02233913,
         0.02808546,  0.04386901, -0.01577348, -0.04859953,  0.04986824],
       [ 0.0414227 , -0.00700275, -0.01070601,  0.03538385, -0.03773081,
         0.01695851, -0.01495393, -0.02533355, -0.0110355 , -0.0106918 ],
       [ 0.00632419, -0.02820213,  0.04238944,  0.02549303, -0.02546762,
         0.02281722, -0.04150204,  0.04794059